"""
Django settings for DjangoAdmin project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xdh=3nspgh^#(+yt(h+-_c(hh%ep1nl8q(2%pqbgi^w_xisv0%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'onlinesolve.net', 'www.onlinesolve.net']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'tiktok_live',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sitemaps',
   


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
                'django.middleware.locale.LocaleMiddleware',  # çoklu dil desteği için eklenmeli
                'django.middleware.common.CommonMiddleware',

 
               
]

ROOT_URLCONF = 'DjangoAdmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoAdmin.wsgi.application'
ASGI_APPLICATION = 'DjangoAdmin.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
        'CONFIG': {}
    }
}

# Login not required - TikFinity style
LOGIN_URL = '/tiktok/setup/'
LOGIN_REDIRECT_URL = '/tiktok/'
LOGOUT_REDIRECT_URL = '/tiktok/setup/'

# TikTok OAuth Settings
TIKTOK_CLIENT_KEY = 'awetpevtlfsy47tp'  # Add your TikTok Client Key here
TIKTOK_CLIENT_SECRET = 'Nr5j2AlDuFE5dhDzFBh7RkGLn2afajy1'  # Add your TikTok Client Secret here
TIKTOK_REDIRECT_URI = 'https://onlinesolve.net/tiktok/auth/tiktok/callback/'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# LOCALE_PATHS = [
#     BASE_DIR / 'locale/',
# ]

from django.utils.translation import gettext_lazy as _

LANGUAGES = (
    ('af', ('Afrikaans')),
    ('sq', ('Albanian')),
    #('ar', ('Arabic')),
    #('hy', ('Armenian')),
    ('az', ('Azerbaijani')),
    ('eu', ('Basque')),
    #('be', ('Belarusian')),
    #('bn', ('Bengali')),
    ('bs', ('Bosnian')),
    #('bg', ('Bulgarian')),
    ('ca', ('Catalan')),
    #('zh-hans', ('Simplified Chinese')),
    #('zh-hant', ('Traditional Chinese')),
    ('hr', ('Croatian')),
    ('cs', ('Czech')),
    ('da', ('Danish')),
    ('nl', ('Dutch')),
    ('en', ('English')),
    ('eo', ('Esperanto')),
    ('et', ('Estonian')),
    #('fa', ('Persian')),
    ('fi', ('Finnish')),
    ('fr', ('French')),
    ('gl', ('Galician')),
    #('ka', ('Georgian')),
    ('de', ('German')),
    #('el', ('Greek')),    
    #('he', ('Hebrew')),
    #('hi', ('Hindi')),
    ('hu', ('Hungarian')),
    ('is', ('Icelandic')),
    ('id', ('Indonesian')),
    ('ga', ('Irish')),
    ('it', ('Italian')),
    #('ja', ('Japanese')),
    #('kn', ('Kannada')),
    #('kk', ('Kazakh')),
    #('km', ('Khmer')),
    #('ko', ('Korean')),
    #('ky', ('Kyrgyz')), 
    #('kg' ,('Kongo'))   
    ('lv', ('Latvian')),
    ('lt', ('Lithuanian')),
    ('lb', ('Luxembourgish')),
    # ('mk', ('Macedonian')),
    ('ms', ('Malay')),
    # ('ml', ('Malayalam')),    
    # ('mr', ('Marathi')),
    #('mn', ('Mongolian')),
    #('ne', ('Nepali')),
    ('no', ('Norwegian Bokmål')),
    #('nn', ('Norwegian Nynorsk')),   #bu dil sıkıntılı olabilir
    ('pl', ('Polish')),
    ('pt', ('Portuguese')),
    #('pa', ('Punjabi')),    
    ('ro', ('Romanian')),
    # ('ru', ('Russian')),
    # ('sr', ('Serbian')),
    ('sk', ('Slovak')),
    ('sl', ('Slovenian')),
    
    ('es', ('Spanish')),
    ('sw', ('Swahili')),
    ('sv', ('Swedish')),
    #('my', ('Malaysia')),
    # ('ta', ('Tamil')),
    # ('tt', ('Tatar')),
    # ('te', ('Telugu')),
    # ('th', ('Thai')),
   
    ('tr', 'Turkish'),
    # ('ug', ('Uyghur')),
    # ('uk', ('Ukrainian')),
    # ('ur', ('Urdu')),
    ('uz', ('Uzbek')),
    ('vi', ('Vietnamese')),
    ('cy', ('Welsh')),




    #('am',('Amharic')),
    #('ay', _('Aymara')),
    #('ce', _('Chechen')),
    #('lo', _('Lao')),
    #('mt', _('Maltese')),
    #('mi', _('Maori')),
    #('oc', _('Occitan')),
    #('om', _('Oromo')),
    #('ps', _('Pashto')),
     #('pt-br',('Brazilian Portuguese')),
    #('qu', _('Quechua')),
    #('so', _('Somali')),
     #('tl', _('Tagalog')),
     #('bo', _('Tibetan')),
    #('tn', _('Tswana')),
    #('wo', _('Wolof')),
    #('xh', _('Xhosa')),
    #('yo', _('Yoruba')),
    #('zza', _('Zazaki')),
    #('zu', _('zulu')),
)

# Language settings
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 year in seconds
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_SECURE = False
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_SAMESITE = 'Lax'


#LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ROSETTA_MESSAGES_SOURCE_LANGUAGE_CODE = 'tr'
ROSETTA_MESSAGES_SOURCE_LANGUAGE_NAME = 'Turkish'

# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Büyük dosyalar için
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
# settings.py


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# Çerez ayarları
#LANGUAGE_COOKIE_NAME = 'django_language'  # Çerez adını burada belirleyebilirsiniz
#LANGUAGE_COOKIE_AGE = 1209600  # Çerezin yaş süresi (2 hafta)
#LANGUAGE_COOKIE_PATH = '/'

# Logging Configuration for TikTok Live
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'stream': 'ext://sys.stdout',  # Use stdout instead of stderr
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'tiktok_live.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',  # Force UTF-8 encoding for file
        },
    },
    'loggers': {
        'tiktok_live': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'TikTokLive': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}