# Generated by Django 5.2.7 on 2025-11-04 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('viewer_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('comment', 'Yorum'), ('like', 'Beğeni'), ('follow', 'Takip'), ('gift', 'Hediye'), ('share', 'Paylaşım'), ('join', 'Katılım')], max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('gift_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gift_value', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiktok_live.livestream')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TikTokAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='livestream',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiktok_live.tiktokaccount'),
        ),
        migrations.CreateModel(
            name='AutoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('response_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiktok_live.tiktokaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger_type', models.CharField(choices=[('comment', 'Yorum'), ('like', 'Beğeni'), ('follow', 'Takip'), ('gift', 'Hediye'), ('share', 'Paylaşım'), ('join', 'Katılım')], max_length=20)),
                ('condition_value', models.IntegerField(default=1)),
                ('action_type', models.CharField(choices=[('message', 'Mesaj Gönder'), ('animation', 'Animasyon Oynat'), ('sound', 'Ses Çal'), ('script', 'Script Çalıştır')], max_length=50)),
                ('action_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiktok_live.tiktokaccount')),
            ],
        ),
    ]
