# Generated by Django 5.2 on 2025-11-04 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_live', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationtrigger',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='autoresponse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='livestream',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='times_triggered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autoresponse',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoresponse',
            name='times_triggered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livestream',
            name='auto_response_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestream',
            name='automation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestream',
            name='is_monitored',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='peak_viewers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livestream',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livestream',
            name='total_gifts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livestream',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livestream',
            name='total_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='can_control_stream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tiktokaccount',
            unique_together={('user', 'username')},
        ),
        migrations.CreateModel(
            name='StreamControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_manage_automations', models.BooleanField(default=True)),
                ('can_manage_responses', models.BooleanField(default=True)),
                ('can_moderate_comments', models.BooleanField(default=False)),
                ('notify_on_gift', models.BooleanField(default=True)),
                ('notify_on_follow', models.BooleanField(default=True)),
                ('notify_threshold_viewers', models.IntegerField(default=100)),
                ('auto_start_monitoring', models.BooleanField(default=True)),
                ('save_interactions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream_control', to='tiktok_live.tiktokaccount')),
            ],
        ),
    ]
