# Generated by Django 5.2.7 on 2025-11-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_live', '0003_tiktokaccount_is_verified_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCommands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_enabled', models.BooleanField(default=True)),
                ('help_command', models.CharField(default='!help', max_length=50)),
                ('get_points_enabled', models.BooleanField(default=True)),
                ('get_points_command', models.CharField(default='!score', max_length=50)),
                ('transfer_points_enabled', models.BooleanField(default=True)),
                ('transfer_points_command', models.CharField(default='!send', max_length=50)),
                ('spin_enabled', models.BooleanField(default=True)),
                ('spin_command', models.CharField(default='!spin', max_length=50)),
                ('coin_drop_enabled', models.BooleanField(default=True)),
                ('coin_drop_command', models.CharField(default='!coindrop', max_length=50)),
                ('custom_commands_enabled', models.BooleanField(default=True)),
                ('custom_commands_command', models.CharField(default='!commands', max_length=50)),
                ('custom_sub_commands_enabled', models.BooleanField(default=True)),
                ('custom_sub_commands_command', models.CharField(default='!subcommands', max_length=50)),
                ('custom_user_commands_enabled', models.BooleanField(default=True)),
                ('custom_user_commands_command', models.CharField(default='!mycommands', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Commands Configuration',
                'verbose_name_plural': 'Chat Commands Configurations',
            },
        ),
    ]
