# Generated by Django 5.2 on 2025-11-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_live', '0008_tts'),
    ]

    operations = [
        # Skip migration - will handle database issues differently
    ]
